import ical, { VEvent, ParameterValue } from "node-ical";
import {
  upsertCalendarEvent,
  deleteStaleCalendarEvents,
  createTask,
  findTaskBySourceEventId,
  updateTask,
} from "@/lib/db/queries";
import {
  toUTC,
  getCalendarParts,
  formatForDisplay,
  DISPLAY_DATETIME,
} from "@/lib/timezone";
import {
  isAssessmentTitle,
  parseCanvasTitle,
} from "@/lib/calendar/assessments";
import { toEndOfDayLocal } from "@/lib/calendar/canvas-helpers";
import type { CalendarSyncResult } from "@/types";

// Recognize prep tasks auto-generated by the FIRST version of this adapter,
// so we can refresh their title/description in-place after the cleanup.
// Any description that starts with this marker is known-safe to overwrite.
const LEGACY_AUTO_PREP_DESC_PREFIX =
  "Auto-generated from Canvas. Original event:";

const MAX_EVENTS = 500;

// Canvas assignment/quiz/discussion UIDs contain these substrings
const ASSIGNMENT_UID_PATTERNS = ["assignment", "quiz", "discussion_topic"];

function isAssignmentEvent(uid: string): boolean {
  return ASSIGNMENT_UID_PATTERNS.some((p) => uid.includes(p));
}

/**
 * Prep task deadline = 10:00 PM local on the day BEFORE the event starts.
 * Gives the user the evening before to prep without forcing same-day crunch.
 * Returns null if the computed prep time is in the past.
 */
function computePrepDeadline(
  eventStart: Date,
  timezone: string
): Date | null {
  const { year, month, day } = getCalendarParts(eventStart, timezone);
  const eventDayMidnight = new Date(
    toUTC(`${year}-${month}-${day}T00:00:00`, timezone)
  );
  // 10:00 PM on the PREVIOUS day = event-day midnight - 2 hours
  const prepDeadline = new Date(
    eventDayMidnight.getTime() - 2 * 60 * 60 * 1000
  );
  if (prepDeadline.getTime() <= Date.now()) return null;
  return prepDeadline;
}

/** Extract the string value from a node-ical ParameterValue field. */
function paramValue(val: ParameterValue | undefined): string | null {
  if (!val) return null;
  if (typeof val === "string") return val;
  return val.val ?? null;
}

/** Fetch a Canvas .ics feed and return its parsed VEVENT components. */
export async function fetchCanvasEvents(icalUrl: string): Promise<VEvent[]> {
  if (!icalUrl.startsWith("https://")) {
    throw new Error("Canvas iCal URL must use HTTPS");
  }

  const response = await fetch(icalUrl, {
    headers: { Accept: "text/calendar" },
    cache: "no-store",
    signal: AbortSignal.timeout(15000),
  });

  if (!response.ok) {
    throw new Error(
      `Failed to fetch Canvas calendar: ${response.status} ${response.statusText}`
    );
  }

  const icsText = await response.text();
  const parsed = ical.sync.parseICS(icsText);

  const events: VEvent[] = [];
  for (const key of Object.keys(parsed)) {
    const component = parsed[key];
    if (component && "type" in component && component.type === "VEVENT") {
      events.push(component as VEvent);
    }
  }
  return events;
}

/**
 * Return the distinct course codes found in a Canvas feed's event titles
 * (e.g. ["ANTH104", "ENGL204"]), for the selective-course-import picker.
 * Events whose title doesn't carry a recognizable `[SEM-DEPT###-SECTION]`
 * tag are excluded — they have no course to attribute them to.
 */
export async function listCanvasCourses(icalUrl: string): Promise<string[]> {
  const events = await fetchCanvasEvents(icalUrl);
  const courses = new Set<string>();
  for (const event of events) {
    const title = paramValue(event.summary);
    if (!title) continue;
    const { courseCode } = parseCanvasTitle(title);
    if (courseCode) courses.add(courseCode);
  }
  return Array.from(courses).sort();
}

/** Build the prep task's title/description from the raw Canvas event title. */
function buildPrepTaskFields(
  rawTitle: string,
  eventStart: Date,
  timezone: string
): { title: string; description: string } {
  const { cleanTitle, assessmentType, courseCode } = parseCanvasTitle(rawTitle);
  const dueStr = formatForDisplay(eventStart, timezone, DISPLAY_DATETIME);

  const descParts: string[] = [];
  if (courseCode && assessmentType) {
    descParts.push(`${courseCode} ${assessmentType}`);
  } else if (courseCode) {
    descParts.push(courseCode);
  } else if (assessmentType) {
    descParts.push(assessmentType);
  }
  descParts.push(`Due ${dueStr}`);

  return {
    title: `Prep: ${cleanTitle}`,
    description: descParts.join(" · "),
  };
}

export async function syncCanvasCalendar(
  userId: string,
  icalUrl: string,
  timezone: string = "America/New_York",
  autoAddCanvasTasks: boolean = true,
  selectedCourses: string[] | null = null
): Promise<CalendarSyncResult> {
  const events = await fetchCanvasEvents(icalUrl);

  if (events.length > MAX_EVENTS) {
    console.warn(
      `[Calendar] Canvas feed has ${events.length} events, limiting to ${MAX_EVENTS}`
    );
    events.length = MAX_EVENTS;
  }

  // Upsert each event
  let synced = 0;
  let prepTasksCreated = 0;
  let prepTasksRefreshed = 0;
  const currentExternalIds: string[] = [];

  for (const event of events) {
    const uid = event.uid;
    if (!uid) continue;

    const title = paramValue(event.summary) ?? "Untitled Event";
    const { courseCode } = parseCanvasTitle(title);

    // Selective course import: a non-null selectedCourses list means "only
    // sync these courses". Events without a recognizable course tag always
    // sync — there's no course to attribute them to. Skipping the uid here
    // (not adding it to currentExternalIds) means deleteStaleCalendarEvents
    // below cleans up any events for a course the user just deselected.
    if (selectedCourses !== null && courseCode !== null && !selectedCourses.includes(courseCode)) {
      continue;
    }

    currentExternalIds.push(uid);

    let startDate =
      event.start instanceof Date ? event.start : new Date(event.start);
    let endDate = event.end
      ? event.end instanceof Date
        ? event.end
        : new Date(event.end)
      : startDate;

    let isAllDay = event.datetype === "date";

    // Convert Canvas assignment all-day events to timed events at 23:59 LOCAL time.
    // Canvas defaults assignments to 11:59 PM in the user's timezone — iCal loses
    // the time for VALUE=DATE entries. We restore it correctly using the user's timezone.
    if (isAllDay && isAssignmentEvent(uid)) {
      startDate = toEndOfDayLocal(startDate, timezone);
      endDate = new Date(startDate);
      isAllDay = false;
    }

    await upsertCalendarEvent({
      userId,
      source: "canvas",
      externalId: uid,
      title,
      description: paramValue(event.description),
      startTime: startDate,
      endTime: endDate,
      location: paramValue(event.location),
      isAllDay,
      category: "school",
    });

    synced++;

    // Auto-generate a prep task for assessment-keyword events (QUIZ/EXAM/
    // etc.). ADHD brains act on tasks, not calendar entries — the prep task
    // closes the activation-energy gap. sourceEventId uniquely ties the task
    // to its originating Canvas event so we don't create duplicates on
    // subsequent syncs, and so we never recreate one the user deleted.
    if (autoAddCanvasTasks && isAssessmentTitle(title)) {
      try {
        const prepDeadline = computePrepDeadline(startDate, timezone);
        if (prepDeadline) {
          const existing = await findTaskBySourceEventId(userId, uid);
          const { title: prepTitle, description: prepDescription } =
            buildPrepTaskFields(title, startDate, timezone);

          if (!existing) {
            await createTask(userId, {
              title: prepTitle,
              description: prepDescription,
              priority: "important",
              energyLevel: "high",
              category: "school",
              deadline: prepDeadline,
              sourceEventId: uid,
            });
            prepTasksCreated++;
          } else if (
            existing.status !== "completed" &&
            !existing.deletedAt &&
            typeof existing.description === "string" &&
            existing.description.startsWith(LEGACY_AUTO_PREP_DESC_PREFIX)
          ) {
            // Retrofit old auto-generated tasks to the cleaner title/description.
            // Guarded to tasks that are still pending AND still carry the exact
            // legacy marker — so we never overwrite a title/description a user
            // has since edited or completed.
            await updateTask(existing.id, userId, {
              title: prepTitle,
              description: prepDescription,
            });
            prepTasksRefreshed++;
          }
        }
      } catch (err) {
        // Don't fail the whole sync if one prep task insert hits a race on
        // the unique index — log and move on.
        console.warn(
          `[Calendar] Prep task creation failed for "${title}":`,
          err
        );
      }
    }
  }

  // Delete stale events no longer in the feed
  const deleted = await deleteStaleCalendarEvents(
    userId,
    "canvas",
    currentExternalIds
  );

  console.log(
    `[Calendar] Canvas sync: ${synced} synced, ${deleted.length} deleted, ${prepTasksCreated} prep tasks created, ${prepTasksRefreshed} prep tasks refreshed`
  );

  return {
    created: synced,
    updated: 0,
    deleted: deleted.length,
    total: currentExternalIds.length,
  };
}
